name: test_mad_soft
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  auto_route: ^8.0.0
  dio: ^5.4.3+1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any 
  json_annotation: ^4.8.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  mobx: ^2.3.3+1
  flutter_mobx: ^2.2.1+1
  flutter_svg: ^2.0.10+1
  zoom_widget: ^2.0.1
  get_storage_info: ^0.1.0
  equatable: ^2.0.5
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  retrofit_generator: '>=7.0.0 <8.0.0' 
  json_serializable: ^6.6.2
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
